### ISSUE TITLE
Maintain this template for the Shaarli community fork

### ISSUE THREAD

**Issue by nodiscc** [Vinm/Blue-theme-for-Shaarli#2]
Hi @Vinm , Shaarli development is now active again on the community fork https://github.com/shaarli/Shaarli. You can read the README to know about the origins of the fork. We are willing to work on changes that will allow users to install third-party templates like yours directly via `git clone` or a simple unzip, without overwriting Shaarli's template. It will become easy to update Shaarli without overwrtigin your template, and vice-versa. It would be cool if you joined the discussion at https://github.com/shaarli/Shaarli/issues/163 or on https://gitter.im/shaarli/Shaarli to make your template compatible with this, and ensure it works with the latest fork. Then I could create a repository for your template at https://github.com/shaarli/ and give you write access so you can maintain it.

Interested?

**Comment by Vinm** [comment]
Hello !

I answer to tell you that the theme for Shaarli I made few years ago is not very good, and is bad coded. If you want to use it, you can, but I advise you to don't use it because it is not responsive and not very user-friendly.

Do what you want ;)
Regards.

**Comment by nodiscc** [comment]
@Vinm Thanks for your reply! People have shown interest in updating their templates to make them compatible (https://github.com/shaarli/Shaarli/issues/163). I understand your template is not maintained anymore, thanks anyway, we'll keep it listed at https://github.com/shaarli/Shaarli/wiki#related-software if you or someone wants to work on it again someday.

You're welcome anytime on the issue tracker for any idea/request you may have.
